environment:
  PYTHONASYNCIODEBUG: "1"
  KAFKA_VERSION: "0.10.2.1"
  SCALA_VERSION: "2.11"
  matrix:
    - PYTHON: "C:\\Python35"
      SNAPPY_WHEEL: "tools\\python_snappy-0.5.4-cp35-cp35m-win32.whl"
    - PYTHON: "C:\\Python35-x64"
      SNAPPY_WHEEL: "tools\\python_snappy-0.5.4-cp35-cp35m-win_amd64.whl"
    - PYTHON: "C:\\Python36"
      SNAPPY_WHEEL: "tools\\python_snappy-0.5.4-cp36-cp36m-win32.whl"
    - PYTHON: "C:\\Python36-x64"
      SNAPPY_WHEEL: "tools\\python_snappy-0.5.4-cp36-cp36m-win_amd64.whl"
    - PYTHON: "C:\\Python37"
      SNAPPY_WHEEL: "tools\\python_snappy-0.5.4-cp37-cp37m-win32.whl"
    - PYTHON: "C:\\Python37-x64"
      SNAPPY_WHEEL: "tools\\python_snappy-0.5.4-cp37-cp37m-win_amd64.whl"

image: Visual Studio 2017

install:
- "%PYTHON%\\python.exe -m pip install %SNAPPY_WHEEL%"
- "%PYTHON%\\python.exe -m pip install -r requirements-win-test.txt"
- "%PYTHON%\\python.exe setup.py develop"

build: off

test_script:
- "%PYTHON%\\python.exe -c \"import sys; print(sys.version)\""
- "%PYTHON%\\python.exe -m pytest -sv --no-print-logs --cov=aiokafka --cov-report=xml --junit-xml=results.xml --docker-image=aiolibs/kafka:%SCALA_VERSION%_%KAFKA_VERSION% tests"
- "set AIOKAFKA_NO_EXTENSIONS=x"
- "%PYTHON%\\python.exe -m pytest -sv --no-print-logs --cov=aiokafka --cov-report=xml:coverage-no-extension.xml --junit-xml=results-no-extension.xml --docker-image=aiolibs/kafka:%SCALA_VERSION%_%KAFKA_VERSION% tests"

on_finish:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path results.xml))

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path results-no-extension.xml))
- "%PYTHON%\\python.exe -m pip install codecov"
- "%PYTHON%\\python.exe -m codecov -f \"coverage.xml\""
- "%PYTHON%\\python.exe -m codecov -f \"coverage-no-extension.xml\""
